# Generated by Django 6.0.7 on 2026-08-07 05:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('location_label', models.CharField(blank=True, help_text='Human readable label for the pinned point.', max_length=255)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_index=True, max_length=3)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, help_text='Whole blood donation requires at least 50 kg.', null=True, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(250.0)])),
                ('height_cm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100.0), django.core.validators.MaxValueValidator(250.0)])),
                ('bio', models.TextField(blank=True, help_text='A short note shown to recipients.', max_length=500)),
                ('max_travel_km', models.FloatField(default=15.0, help_text='Furthest the donor is willing to travel to donate.', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(500.0)])),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available to donate'), ('BUSY', 'Temporarily unavailable'), ('RESTING', 'Resting after donation'), ('PAUSED', 'Paused / hidden')], db_index=True, default='AVAILABLE', max_length=20)),
                ('available_from_hour', models.PositiveSmallIntegerField(default=8, help_text="Start of the donor's preferred contact window (0-23).", validators=[django.core.validators.MaxValueValidator(23)])),
                ('available_to_hour', models.PositiveSmallIntegerField(default=21, help_text="End of the donor's preferred contact window (0-23).", validators=[django.core.validators.MaxValueValidator(23)])),
                ('is_searchable', models.BooleanField(default=True, help_text='Uncheck to hide completely from recipient map searches.')),
                ('has_chronic_illness', models.BooleanField(default=False)),
                ('on_medication', models.BooleanField(default=False)),
                ('recently_tattooed', models.BooleanField(default=False, help_text='Tattoo or piercing in the last 6 months.')),
                ('is_pregnant', models.BooleanField(default=False)),
                ('is_smoker', models.BooleanField(default=False)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('invitations_received', models.PositiveIntegerField(default=0)),
                ('invitations_accepted', models.PositiveIntegerField(default=0)),
                ('invitations_declined', models.PositiveIntegerField(default=0)),
                ('invitations_expired', models.PositiveIntegerField(default=0)),
                ('completed_donations', models.PositiveIntegerField(default=0, help_text='Accepted invitations that ended in a real donation.')),
                ('no_shows', models.PositiveIntegerField(default=0, help_text='Accepted invitations the donor did not honour.')),
                ('total_response_seconds', models.BigIntegerField(default=0, help_text='Cumulative response latency, used for the mean.')),
                ('responses_counted', models.PositiveIntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Identity/medical documents checked by staff.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'donor profile',
                'verbose_name_plural': 'donor profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donated_on', models.DateField(db_index=True)),
                ('units', models.PositiveSmallIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('blood_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='blood_requests.bloodrequest')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_donations', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donorprofile')),
            ],
            options={
                'verbose_name': 'donation record',
                'verbose_name_plural': 'donation records',
                'ordering': ['-donated_on'],
            },
        ),
        migrations.AddIndex(
            model_name='donorprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='donor_lat_lng_idx'),
        ),
        migrations.AddIndex(
            model_name='donorprofile',
            index=models.Index(fields=['blood_group', 'availability_status'], name='donor_group_avail_idx'),
        ),
        migrations.AddConstraint(
            model_name='donorprofile',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90.0), ('latitude__lte', 90.0)), _connector='OR'), name='donor_latitude_in_range'),
        ),
        migrations.AddConstraint(
            model_name='donorprofile',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180.0), ('longitude__lte', 180.0)), _connector='OR'), name='donor_longitude_in_range'),
        ),
    ]
