# Generated by Django 6.0.7 on 2026-08-07 05:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('location_label', models.CharField(blank=True, help_text='Human readable label for the pinned point.', max_length=255)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('patient_name', models.CharField(max_length=120)),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(130)])),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_index=True, max_length=3)),
                ('units_required', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('units_fulfilled', models.PositiveSmallIntegerField(default=0)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine (within a week)'), ('URGENT', 'Urgent (within 24 hours)'), ('CRITICAL', 'Critical (immediate)')], db_index=True, default='URGENT', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SEARCHING', 'Searching for donors'), ('PARTIAL', 'Partially matched'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='SEARCHING', max_length=20)),
                ('needed_by', models.DateTimeField(help_text='Deadline after which blood is no use.')),
                ('hospital_name', models.CharField(blank=True, help_text='Where the donation should take place.', max_length=200)),
                ('reason', models.TextField(blank=True, max_length=1000)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('search_radius_km', models.FloatField(default=10.0, help_text='Radius used when searching the map for donors.', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(500.0)])),
                ('notes_for_donor', models.TextField(blank=True, max_length=500)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='hospitals.hospitalprofile')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='recipients.recipientprofile')),
            ],
            options={
                'verbose_name': 'blood request',
                'verbose_name_plural': 'blood requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting response'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Donation completed')], db_index=True, default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Personal note from the requester.', max_length=500)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('match_score', models.FloatField(default=0.0, help_text='AI match score at the moment the invitation was sent.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('rank_position', models.PositiveSmallIntegerField(blank=True, help_text='Where this donor sat in the ranked list.', null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=dict, help_text='Feature vector that produced match_score, for retraining.')),
                ('score_breakdown', models.JSONField(blank=True, default=dict, help_text='Per-feature contributions, used for the score explanation UI.')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_requests', to='blood_requests.bloodrequest')),
            ],
            options={
                'verbose_name': 'donor request',
                'verbose_name_plural': 'donor requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
