# Generated by Django 6.0.7 on 2026-08-07 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donorrequest',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='donors.donorprofile'),
        ),
        migrations.AddField(
            model_name='donorrequest',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['latitude', 'longitude'], name='req_lat_lng_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['status', 'urgency'], name='req_status_urgency_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['blood_group', 'status'], name='req_group_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='bloodrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hospital__isnull', True), ('recipient__isnull', False)), models.Q(('hospital__isnull', False), ('recipient__isnull', True)), _connector='OR'), name='request_has_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='bloodrequest',
            constraint=models.CheckConstraint(condition=models.Q(('units_fulfilled__lte', models.F('units_required'))), name='fulfilled_not_over_required'),
        ),
        migrations.AddIndex(
            model_name='donorrequest',
            index=models.Index(fields=['donor', 'status'], name='dreq_donor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='donorrequest',
            index=models.Index(fields=['blood_request', 'status'], name='dreq_request_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='donorrequest',
            constraint=models.UniqueConstraint(fields=('blood_request', 'donor'), name='unique_invitation_per_donor'),
        ),
    ]
