# Generated by Django 6.0.7 on 2026-08-07 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(unique=True)),
                ('weights', models.JSONField(default=dict, help_text='Feature name -> learned coefficient.')),
                ('bias', models.FloatField(default=0.0)),
                ('training_samples', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Holdout evaluation: accuracy, AUC, log loss, base rate.')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('trained_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'ranking model',
                'verbose_name_plural': 'ranking models',
                'ordering': ['-version'],
            },
        ),
    ]
