# Generated by Django 6.0.7 on 2026-08-07 05:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('location_label', models.CharField(blank=True, help_text='Human readable label for the pinned point.', max_length=255)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('hospital_name', models.CharField(db_index=True, max_length=200)),
                ('license_number', models.CharField(help_text='Official registration number, used for verification.', max_length=100, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('has_blood_bank', models.BooleanField(default=False, help_text='Can this facility store and dispense blood?')),
                ('is_24_hours', models.BooleanField(default=False)),
                ('bed_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='License checked by platform staff.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hospital profile',
                'verbose_name_plural': 'hospital profiles',
                'ordering': ['hospital_name'],
            },
        ),
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('units_available', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('critical_threshold', models.PositiveIntegerField(default=5, help_text='Below this level the group is flagged as low stock.')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hospitals.hospitalprofile')),
            ],
            options={
                'verbose_name': 'blood inventory item',
                'verbose_name_plural': 'blood inventory',
                'ordering': ['blood_group'],
            },
        ),
        migrations.AddIndex(
            model_name='hospitalprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='hosp_lat_lng_idx'),
        ),
        migrations.AddConstraint(
            model_name='bloodinventory',
            constraint=models.UniqueConstraint(fields=('hospital', 'blood_group'), name='unique_hospital_blood_group'),
        ),
    ]
