# Generated by Django 6.0.7 on 2026-08-07 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('REQ_RECV', 'New blood request'), ('REQ_ACC', 'Donor accepted'), ('REQ_DEC', 'Donor declined'), ('REQ_CAN', 'Request cancelled'), ('DON_LOG', 'Donation recorded'), ('ELIGIBLE', 'Eligible to donate again')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, max_length=1000)),
                ('url', models.CharField(blank=True, help_text='Where clicking the notification goes.', max_length=300)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('blood_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='blood_requests.bloodrequest')),
                ('donor_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='blood_requests.donorrequest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notif_recip_read_idx')],
            },
        ),
    ]
